baseurl = "https://porquesim.netlify.app"
title = "Porque SIM"
theme = "hugo-theme-cleanwhite"
languageCode = "pt-BR"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "assets/bg-slider-mundo.jpg"
  SEOTitle = "Porque SIM"
  description = ""
  keyword = ""
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = ""
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Porque SIM ONG"
  sidebar_avatar = "assets/logo.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 1

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  reward = false

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = true
  email          = "youremail@gmail.com"
  twitter       = "https://twiter.com/..."
  linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  instagram     = "https://instagram.com/..."
  github         = "https://github.com/pqsim"

  [[params.addtional_menus]]
  title =  "Quem Somos"
  href =  "/pages/quem-somos/"

  [[params.addtional_menus]]
  title =  "Inscreva-se"
  href =  "/pages/inscreva-se/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
